{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# importing tkinter\n",
    "from tkinter import *\n",
    "# initializing tkinter\n",
    "root = Tk()\n",
    "# setting geometry\n",
    "root.geometry(\"350x350\")\n",
    "# setting title\n",
    "root.title(\"Get Covid-19 Data Country Wise\")\n",
    "\n",
    "# function which will get covid data and will show it\n",
    "def showdata():\n",
    "    # importing matplotlib which will be used to show data graphically\n",
    "    from matplotlib import pyplot as plt\n",
    "    # to scale the data we are importing patches\n",
    "    import matplotlib.patches as mpatches\n",
    "    # importing covid library\n",
    "    from covid import Covid\n",
    "    # initializing covid library\n",
    "    covid = Covid()\n",
    "    # declaring empty lists to store different data sets\n",
    "    cases = []\n",
    "    confirmed = []\n",
    "    active = []\n",
    "    deaths = []\n",
    "    recovered = []\n",
    "    # using try and except to run program without errors\n",
    "    try:\n",
    "        # updating root\n",
    "        root.update()\n",
    "        # getting countries names entered by the user\n",
    "        countries = data.get()\n",
    "        # removing white spaces from the start and end of the string\n",
    "        country_names = countries.strip()\n",
    "        # replacing white spaces with commas inside the string\n",
    "        country_names = country_names.replace(\" \", \",\")\n",
    "        # splitting the string to store names of countries\n",
    "        # as a list \n",
    "        country_names = country_names.split(\",\")\n",
    "        # for loop to get all countries data\n",
    "        for x in country_names:\n",
    "            # appending countries data one-by-one in cases list \n",
    "            # here, the data will be stored as a dictionary\n",
    "            # for one country i.e. for each country\n",
    "            # there will be one dictionary in the list\n",
    "            # which will contain the whole information\n",
    "            # of that country\n",
    "            cases.append(covid.get_status_by_country_name(x))\n",
    "            # updating the root\n",
    "            root.update()\n",
    "        # for loop to get one country data stored as dict in list cases\n",
    "        for y in cases:\n",
    "            # storing every Country's confirmed cases in the confirmed list\n",
    "            confirmed.append(y[\"confirmed\"])\n",
    "            # storing every Country's active cases in the active list\n",
    "            active.append(y[\"active\"])\n",
    "            # storing every Country's deaths cases in the deaths list\n",
    "            deaths.append(y[\"deaths\"])\n",
    "            # storing every Country's recovered cases in the recovered list\n",
    "            recovered.append(y[\"recovered\"])\n",
    "        # marking the color information on scaleusing patches\n",
    "        confirmed_patch = mpatches.Patch(color='green', label='confirmed')\n",
    "        recovered_patch = mpatches.Patch(color='red', label='recovered')\n",
    "        active_patch = mpatches.Patch(color='blue', label='active')\n",
    "        deaths_patch = mpatches.Patch(color='black', label='deaths')\n",
    "        # plotting the scale on graph using legend()\n",
    "        plt.legend(handles=[confirmed_patch, recovered_patch, active_patch, deaths_patch])\n",
    "        # showing the data using graphs\n",
    "        # this whole for loop section is related to matplotlib\n",
    "        for x in range(len(country_names)):\n",
    "            plt.bar(country_names[x], confirmed[x], color='green')\n",
    "            if recovered[x] > active[x]:\n",
    "                plt.bar(country_names[x], recovered[x], color='red')\n",
    "                plt.bar(country_names[x], active[x], color='blue')\n",
    "            else:\n",
    "                plt.bar(country_names[x], active[x], color='blue')\n",
    "                plt.bar(country_names[x], recovered[x], color='red')\n",
    "            plt.bar(country_names[x], deaths[x], color='black')\n",
    "        # setting the title of the graph\n",
    "        plt.title('Current Covid Cases')\n",
    "        # giving label to x direction of graph\n",
    "        plt.xlabel('Country Name')\n",
    "        # giving label to y direction of graph\n",
    "        plt.ylabel('Cases(in millions)')\n",
    "        # showing the full graph\n",
    "        plt.show()\n",
    "    except Exception as e:\n",
    "        # asking user to enter correct details\n",
    "        # during entering the country names on GUI\n",
    "        # please differentiate the country names\n",
    "        # with spaces or comma but not with both\n",
    "        # otherwise you will come to this section\n",
    "        data.set(\"Enter correct details again\")\n",
    "\n",
    "\n",
    "Label(root, text=\"Enter all countries names\\nfor whom you want to get\\ncovid-19 data\", font=\"Consolas 15 bold\").pack()\n",
    "Label(root, text=\"Enter country name:\").pack()\n",
    "data = StringVar()\n",
    "data.set(\"Seperate country names using comma or space(not both)\")\n",
    "entry = Entry(root, textvariable=data, width=50).pack()\n",
    "Button(root, text=\"Get Data\", command=showdata).pack()\n",
    "root.mainloop()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
